export const BACK = 'FILESYSTEM_ACTION::BACK';
export const FORWARD = 'FILESYSTEM_ACTION::FORWARD';
export const SET_FOLDER_DATA = 'FILESYSTEM_ACTION::SET_FOLDER_DATA';
export const GET_FOLDER_DATA = 'FILESYSTEM_ACTION::GET_FOLDER_DATA';
