export const BACK = 'FILESYSTEM_ACTION::BACK';
export const FORWARD = 'FILESYSTEM_ACTION::FORWARD';
export const SET_FOLDER_DATA = 'FILESYSTEM_ACTION::SET_FOLDER_DATA';
export const GET_FOLDER_DATA = 'FILESYSTEM_ACTION::GET_FOLDER_DATA';
export const SEARCH_FOLDER_FILE = 'FILESYSTEM_ACTION::SEARCH_FOLDER_FILE';
export const DOWNLOAD_FILE = 'FILESYSTEM_ACTION::DOWNLOAD_FILE';
export const GET_VERSIONS = 'FILESYSTEM_ACTION::GET_VERSIONS';
