export const BACK = 'FILESYSTEM_ACTION::BACK';
export const FORWARD = 'FILESYSTEM_ACTION::FORWARD';
export const CREATE_DIRECTORY = 'FILESYSTEM_ACTION::CREATE_DIRECTORY';
export const GET_DIRECTORY_DATA = 'FILESYSTEM_ACTION::GET_DIRECTORY_DATA';
